In [8]:
!pip install numpy
!pip install pandas

Requirement already satisfied: numpy in c:\users\hp\anaconda3\lib\site-packages (1.26.4)
Requirement already satisfied: pandas in c:\users\hp\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\hp\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [ ]:
import pandas as pd 
import numpy as np

s = pd.Series() 
print("Pandas Series: ", s) 
data = np.array(['g', 'e', 'e', 'k', 's']) 
  
s = pd.Series(data) 
print("Pandas Series:\n", s)

Pandas Series:  Series([], dtype: object)
Pandas Series:
 0    g
1    e
2    e
3    k
4    s
dtype: object

In [ ]:
import pandas as pd
   
df = pd.DataFrame() 
print(df)
lst = ['Geeks', 'For', 'Geeks', 'is', 'portal', 'for', 'Geeks'] 
  
df = pd.DataFrame(lst) 
print(df)

Empty DataFrame
Columns: []
Index: []
        0
0   Geeks
1     For
2   Geeks
3      is
4  portal
5     for
6   Geeks

In [ ]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Hp\OneDrive\New folder\PDA\data.csv")
print(df.head())

In [11]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       7 non-null      object
dtypes: object(1)
memory usage: 188.0+ bytes
None

In [12]:
print(df.isnull().sum())
df = df.fillna(0)

0    0
dtype: int64

In [ ]:
ages = df[df['age'] > 25]
print(ages)

KeyError: 'age'

In [ ]:
df['total'] = df['a'] + df['b']
print(df.head())

NameError: name 'df' is not defined

In [ ]:
res = df.groupby('category')['sales'].sum()
print(res)

KeyError: 'category'

:

In [14]:
import pandas as pd 
s = pd.Series([10, 20, 30, 40])

In [15]:
s = pd.Series([85, 90, 78], index=["A", "B", "C"])

In [ ]:
s[0]        
# Access first element 
s["A"]     # Access by label

C:\Users\Hp\AppData\Local\Temp\ipykernel_19164\4108854481.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[0]

85

In [ ]:
s.mean(), s.max(), s.min()

(84.33333333333333, 90, 78)

In [16]:
data = { 
"Name": ["Amit", "Riya", "Karan"], 
"Marks": [85, 90, 78] 
} 
df = pd.DataFrame(data)

In [ ]:
df["Name"]

0     Amit
1     Riya
2    Karan
Name: Name, dtype: object

In [ ]:
df.loc[0] 
df.iloc[1]

Name     Riya
Marks      90
Name: 1, dtype: object

In [ ]:
df["Grade"] = ["A", "A+", "B"]

In [ ]:
df.drop("Grade", axis=1)

    Name  Marks
0   Amit     85
1   Riya     90
2  Karan     78

In [ ]:
df[df["Marks"] > 80]

   Name  Marks Grade
0  Amit     85     A
1  Riya     90    A+

In [ ]:
df.describe()

           Marks
count   3.000000
mean   84.333333
std     6.027714
min    78.000000
25%    81.500000
50%    85.000000
75%    87.500000
max    90.000000